apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice-pod
  template:
    metadata:
      labels:
        app: my-microservice-pod
    spec:
      containers:
      - name: my-microservice-container
        image: johneriksson13/my_microservice:1.1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: my-microservice-service
spec:
  selector:
    app: my-microservice-pod
  ports:
  - port: 4100
    targetPort: 3100
