apiVersion: v1
kind: ConfigMap
metadata:
  name: my-database-config
  labels:
    app: my-database-pod
data:
  POSTGRES_DB: my_database
  POSTGRES_USER: my_user
---
apiVersion: v1
kind: Secret
metadata:
  name: my-database-secret
  labels:
    app: my-database-pod
type: Opaque
# echo -n 'my_password' | base64
data:
  POSTGRES_PASSWORD: bXlfcGFzc3dvcmQ=
