apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-backend-pod
  template:
    metadata:
      labels:
        app: my-backend-pod
    spec:
      containers:
      - name: my-backend-container
        image: johneriksson13/my_backend:1.1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  type: LoadBalancer
  selector:
    app: my-backend-pod
  ports:
  - port: 4000
    targetPort: 3000
